dist: xenial
sudo: false
cache: pip

language: python

matrix:
  include:
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.4"
      env: TOXENV=py34
    - python: "2.7"
      env: TOXENV=py27
    - env: TOXENV=lint

install:
  - pip install tox

script:
  - tox

after_success:
  - if [ $TOXENV != lint ]; then pip install coveralls; fi
  - if [ $TOXENV == py27 ]; then pip install requests --upgrade; fi
  - if [ $TOXENV != lint ]; then coveralls; fi

deploy:
  provider: pypi
  user: chrisw
  password:
    secure: BManEisxNCN966HPz8J/oYzFBPuTPFP212d8rUjv9p/W96pT0zWlO9paDce67nZiYWb7Khzg7fF5WSFpYRKsvB4a370KpTYbsAb8EPx7DUBPsz7qFC8B6EUbCXfwbe68XwPugenREby8vEtywUqxzge2SNVRPfH+wKio2hUcfEo=
  on:
    tags: true
    repo: python-excel/xlrd
    python: "3.5"
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
